[mgr]
show_hidden = true
ratio = [2,4,3]
sort_by = "natural"
sort_dir_first = true
linemode = "size_and_mtime"
show_symlink = true

[preview]
tab_size = 4
image_quality = 90

[opener]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" }
]

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
